const Router = require('express')
const router = new Router()
const CompanysRouter = require('./CompanysRouter')
const ExpectedShiftRouter = require('./ExpectedShifsRouter')
const NoteRouter = require('./NoteRouter')
const PositionsRouter = require('./PositionsRouter')
const ShiftsRouter = require('./ShiftsRouter')
const UserRouter = require('./UserRouter')
const WorkersRouter = require('./WorkersRouter')
const FirmaRouter = require('./FirmaRoute')
const WorkStatus = require('./WorkStatusRouter')
const WorkPermit = require('./WorkPermitRouter')
const CompanyType = require('./CompanyTypeRouter')
const WorkHoursTemplates = require('./WorkHourTemplatesRouter')

router.use('/user',UserRouter)
router.use('/workers',WorkersRouter)
router.use('/shifts',ShiftsRouter)
router.use('/positions',PositionsRouter)
router.use('/note',NoteRouter)
router.use('/companys',CompanysRouter)
router.use('/expectedShifts',ExpectedShiftRouter)
router.use('/firma', FirmaRouter)
router.use('/workStatus', WorkStatus)
router.use('/workPermit', WorkPermit)
router.use('/companyType', CompanyType)
router.use('/workHoursTemplates', WorkHoursTemplates)
module.exports = router